### ISSUE TITLE
gpio: need libsoc_gpio_wait_change() libsoc_gpio_callback_change() for devices that don't support interrupts

### ISSUE THREAD

**Issue by brunnels** [jackmitch/libsoc#23]
I2C gpio expanders like the gpio-pcf857x don't typically have interrupt support so there is no /sysfs/class/gpio/gpio248/edge.  I was thinking it should still be possible to provide similar functionality as the interrupt methods using poll() to check for a value change?

The  libsoc_gpio_get_edge() and libsoc_gpio_set_edge() methods should also check if the edge file is present and throw an error if not.  Right now you get a "libsoc-file-debug: No such file or directory"

**Comment by jackmitch** [comment]
Let me have a think; this would require implementing a userspace interrupt style piece of code as we can't just poll the input, we must poll the input and check against the selected interuppt edge trigger etc. I can't help feeling this might be better done in the application rather than the library.

**Comment by jackmitch** [comment]
With regards to to errors, get_edge returns EDGE_ERROR if the file isn't found, and set_egde returns EXIT_FAILURE if the edge file isnt found so these cases are handled; although it could be more consistent.
